### ISSUE TITLE
Include tobii_research_addons in other package

### ISSUE THREAD

**Issue by yh-luo** [tobiipro/prosdk-addons-python#4]
Hi,
I've been using the amazing Tobii Pro SDK with [PsychoPy](https://www.psychopy.org/) to collect eye-tracking data for a while.
I wonder if it's appropriate to include the add-on in my package (GPL v3 licensed) to provide the validation procedure?
The contents will not be modified, the copyright & license will be retained and noticed. 

Because the add-on is not on PyPI, I think if I provide a copy of this add-on in my package would be easier for the users to use.
If that's ok, please let me know! Or I will provide a link to notice the users to acquire this add-on to use the validation procedure.

Many thanks,
Yu-Han

**Comment by ohadcn** [comment]
Since this code is attached a [license](https://github.com/tobiipro/prosdk-addons-python/blob/master/LICENSE) file, and the license file declare it being under apache license, and since apache allow integration with GPL v3 licensed code - I guess you can use it.

See this stackoverflow [answer](https://stackoverflow.com/questions/35240968/can-i-license-my-project-under-gpl-when-i-use-apache-licensed-libraries) for more details.

P,S:

I'm not working at Tobii, so this isn't an authoritative answer...

**Comment by jonashogstrom** [comment]
Yes, as far as I can tell, it should not be a problem as long as you follow the requirements in section 4 (redistribution) in the apache2 license. 

/Jonas Högström, Tobii
